src/AgendaView.vala

When selecting a day in the grid, the sorting method of the AgendaView gets the selected date in local timezone, in this form:
YYY-MM-DDT00:00:00[+|-]hhmm
Then the AgendaView proceeds to get the events of this date, using a sorting function that does:
(1) Gets the selected date and converts to UTC
(2) Strips the new date from everything except year, month and day
(3) Generates a time range from what it gets in (2) to the same date plus one day
(4) Gets all events whithin the range generated in (3)
The problem lies in (2), when in timezones at the East respect UTC.
Lets check what happens with two examples with the steps 1-3 described above:
First example: the selected date is 2017-05-17T00:00:00-0600, which is at the West respect UTC timezone
(1) 2017-05-17T00:00:00-0600 to UTC : …

Possible fix for github issue #109: calendar overview shows previous date not the selected date

---

core/Utils.vala

Adding the interval can cause in certain timezones all day events to show up on the wrong day, particularly the day before.

Correctly generate date ranges for all day events (#132)

---

core/Model/CalendarModel.vala
core/Utils.vala

Whilst the user interface shows an export button, the function to export was not implemented, these commits will add this and as such all of the contractors function now (print (#129), compress, email (#80), bluetooth, export). Print just prints the text, however that seems to be the expected behaviour based on trying to print ics files from Files. The exported files may contain some errors namely about having no values for certain fields, however this does not impact usage of the ical file.
Fixes #80 
Fixes #129
Fixes #30

Implement exporting of calendar #30

---

core/Utils.vala

Similarly to #136 the interval being added can cause the agenda view to show the event on the wrong days

Show multi-day all day events correctly #137

---

core/DateRange.vala
core/Model/CalendarModel.vala
core/Utils.vala
src/Grid/CalendarView.vala

Fixes #143 
It appears that the property names XXX_FIRST_PROPERTY and XXX_LAST_PROPERTY are already used by the compiler; use of "first" and "last" as property names in Vala code then produces the error shown in the linked issue.
This was fixed by changing these property names in the vala code.

Avoid property names "first" and "last".

---

src/EventEdition/LocationPanel.vala

see #42 
TO TEST:
1) Open an event with a location set; open Location tab.
2) Cancel
3) Repeat 1) and 2)
In trunk the location entry text becomes garbled and the app may crash.
In branch the entry text is correct each time.

Avoid garbled text and crash in Location Panel.

---

src/EventEdition/LocationPanel.vala

The map currently only displays the location found from the search bar and does not allow setting location through it. This problem was raised by issue #53; as double clicking is used to zoom, I agree with Steffen that the logical method is through dragging. This push will implement this, however note this will not use the exact way which would be through latitude and longitude but rather reverse geocodes to get an address as I think that is a better way of representing the location to the user, even if it loses some accuracy.

Allow setting location using map

---

src/Application.vala
src/MainWindow.vala

Making the grid public is only temporary in order to transition pieces into MainWindow a bit at a time
* move a state restoring conditional up with other state restoring code
* Move the infobar into MainWindow

Add infobar to MainWindow

---

core/Backends/Backend.vala
core/Backends/BackendsManager.vala
core/Backends/LocalBackend.vala
core/Backends/PlacementWidget.vala
plugins/CalDAV/CalDAVBackend.vala
plugins/Google/GoogleBackend.vala

This corrects the address for the Free Software Foundation in the LGPL license headers. I had previously had submitted this in #148 but since it is a small, simple change I decided to separate it out.
Fixes #101

Correct FSF address

---

src/Grid/EventButton.vala
src/Grid/VAutoHider.vala

This sorts the events on the grid according to the Util.compare_events function (it moves non-EventButtons to the end as the only one of those should be the show more label) .
Fixes #94

Sort events on Grid

---

core/Utils.vala
src/Grid/CalendarView.vala
src/Grid/EventButton.vala
src/Grid/Grid.vala
src/Grid/GridDay.vala
src/Grid/VAutoHider.vala

This replaces the remove and re-add behaviour for updating events and directly updates the event on the button. As a result there is no duplication on the event whilst this is going on. This does add quite a bit of complexity when handling multi-day events.
Fixes #127

Update EventButtons directly

---

daemon/Daemon.vala
src/EventEdition/ReminderPanel.vala

This removes email notifications as an option as it isn't implmeneted. It leaves the ComboBox to select notification type for the potential of re-adding it, when it is implemented. 
Closes #177 (Although we probably want to create an issue to add email notifications)

Remove email notifications

---

plugins/CalDAV/CalDAVBackend.vala

When loading a CalDav calendar to edit, it strips the port, so if the user saves a change it will also remove the non-standard port. This shows the port if it is not 80.
Fixes #140 
Fixes #37

Load non-standard ports when editing

---

src/AgendaView.vala
src/Grid/EventButton.vala

This adds the ability to right click events on the grid to edit or remove them, this matches the behaviour of right clicking events in the agenda view.

Allow right clicking EventButtons

---

src/AgendaView.vala

This changes the filter for the selected date events list in agenda to correctly handle repeating events.
Fixes #181

Show event repeats in agenda correctly

---

data/style/calendar.css
src/Grid/Grid.vala
src/Grid/GridDay.vala

Previously GridDays in other months were marked as insensitive, this caused issues when clicking on them and required you to click at the very top (the label) to change month, this resolves this by instead using a css class to style cells that are in other months. A side effect of this push is that the background colour for other months applies, whereas previously the css that should have been applied was not, if this is not a desired result, that rule can easily be removed to just be the grayed out text.
Fixes #74

Correct selecting days in other months

---

src/ImportDialog.vala

This fixes the import behaviour, so that it will import all VEVENTs correctly from an ics file (I had to use the libical iterators so it ended up with a pretty ugly for loop.) Previously it was taking the whole ics file as a single component for one event, which is naturally not the correct behaviour.
Fixes #56 
Fixes #52

Correctly import ics files

---

core/Utils.vala
src/EventEdition/InfoPanel.vala
src/Grid/GridDay.vala

This moves all the iCal.TimeType conversion in utils to the get_local_datetimes_from_icalcomponent to reduce code repetition and modifies the handling of dtends to handle if there is no dtend specified to match the behaviour defined in the spec (https://tools.ietf.org/html/rfc5545#section-3.6.1)
Hopefully this fixes #180

Handle null dtends correctly

---

data/org.pantheon.maya.appdata.xml.in.in

Adds the 0.4 series of releases to the appdata.
Release commits:
0.4.0.2: https://github.com/elementary/calendar/commit/ea2bf947352b9c5dd3311e233680596f9725fd6d
0.4.0.1: https://github.com/elementary/calendar/commit/9e6d7e0b763e61c65503cc115e56b66a30afa1fd
0.4: https://github.com/elementary/calendar/commit/1a2b78dcd80094afa9ee6b6267a12a08c8add956

Add missing releases to appdata

---

core/Utils.vala

This ensures that the days within the first week are added correctly and weeks are not missed in the recurrence due to the start date.
Fixes #72

Correctly generate date ranges for repeat events

---

src/Application.vala

Removes setting of fields for Granite.Application that were used for the about dialog that is now deprecated.

Remove fields for deprecated about dialog

---

daemon/Daemon.vala

Uses the new relative datetime format from Granite for same day notifications, unfortunately it isn't currently as useful for other dates as it doesn't handle say 6 month in the future, so we are better sticking with the existing code for other notifications.

Use relative date format for same day notifications

---

src/Application.vala

The year update shouldn't be controversial at all, but I did change "Maya Developers" to "elementary LLC", particularly if we are renaming to just Calendar and moving to RDNN names under "io.elementary" this makes sense to avoid confusion.

Update version information

---

src/AgendaView.vala

Fallback to char wrapping if word is too long to wrap

---

po/CMakeLists.txt

Corrects the desktop file names used by make pot so that it can run, otherwise the make pot command does not work.

Correct desktop names for make pot

---

AUTHORS

Outdated, GitHub provides more up to date contributor information.

Delete AUTHORS file

---

src/Grid/EventButton.vala
src/Grid/Grid.vala

When an event has repetitions this makes it so right clicking on them in the grid includes remove series and remove occurrence buttons rather than the generic remove, this is to create a simpler way to add exception dates.

Add remove occurrence button

---

src/EventParser/Parsers/ParserEn.vala

Day could be 0 to 1 characters, so "9 march" worked, but "19 march" wouldn't. 
This makes it follow the same logic as the next regular expression: 
https://github.com/elementary/calendar/blob/master/src/EventParser/Parsers/ParserEn.vala#L309

Date regex fix

---

debian/maya-calendar-daemon.install
debian/maya-calendar-daemon.links
debian/maya-calendar.install

Should fix currently failing builds
* Desktops now use RDNN naming
* Icons and CSS use GResource so they don't get installed

Fix metadata changes in packaging

---

core/Utils.vala

Because of https://github.com/elementary/wingpanel-indicator-datetime/pull/71

Utils: Update location of datetime indicator setting

---

data/style/sidebar.css

Eliminate this warning:
(io.elementary.calendar:13709): Gtk-WARNING **: 21:32:17.677: Theme parsing error: sidebar.css:30:21: The :focused pseudo-class is deprecated. Use :focus instead.

Eliminate Gtk warning about :focused

---

data/style/calendar.css
src/Grid/WeekLabels.vala

This adds padding to the Week Number Labels so that it feels less cramped. Initially, I tried `6px` all around, but it felt a little too roomy. I ended up using `3px` as shown in the screenshot below.
Fixes #126 (a little pet peeve of mine)

Add padding to weeknumber labels

---

debian/control

This should [fingers crossed] make it so that the libgeoclue branch builds.

Add libgeoclue as a dependency

---

meson.build
src/EventEdition/LocationPanel.vala
src/meson.build

When adding a new event, the location panel gets initialized with the location of the timezone. This is bad for people like me, who live in Dallas but have a timezone in Chicago. That means every time I add an event with a location, I have to wait for the map to scroll to Chicago, and then I have to type in a location and wait for the map to scroll to Dallas. There are a few things wrong with this:
- The map centers on a city I've never even been to, which is confusing
- The map takes a very long time to scroll to locations
- The zoom level is too far up to be useful
This PR:
I would like to work on another PR that uses some smarter logic to set the zoom level based on address detail (county, city, street, etc.). For now, this fixes #151.

Fix Location Panel Initialization

---

data/style/calendar.css
src/AgendaView.vala
src/Grid/CalendarView.vala
src/Grid/Grid.vala
src/Grid/GridDay.vala
src/Grid/Header.vala

This branch primarily removes Cairo draw functions that were used to draw the borders of the grid. Instead, there is CSS to take care of the drawing.
The only funkiness is in the `CalendarView.vala` where the top left corner had to be filled with a blank label widget in order to draw a border next to the Sunday label. If the Sunday label draws the border, it is not in line with the week number border. Additionally, the blank widget needs to be shown and hidden when the week numbers are revealed/hidden, so it is slightly more complicated than I wish it could be.
What's important here is that it works and it uses less code and more CSS to draw the borders. If anyone has questions, feel free to hit me up.

Remove cairo draws

---

core/Settings/SavedState.vala
src/Application.vala
src/MainWindow.vala

Important to note that this branch doesn't introduce (or fix) #196 
Moves a bunch of UI creation from the application class to the MainWindow class
Also moves window state saving to MainWindow. Doesn't attempt to modernize the schemas other than throttling and using a binding for the pane position

Move things from Application to MainWindow

---

src/SourceDialog/SourceItem.vala
src/SourceDialog/SourceSelector.vala

* Don't noshow deleted message since that causes popover resize jank
* Update the deleted message label when source item names change
* Don't hide buttons when items are not actionable. Instead make insensitive and give explanatory tooltips.
* Give the delete action a destruction action class
* Move close button to the left in undo message
* Use a over/under left-swipe kind of animation
* Remove unnecessary casts
* Organize

Redesign removable source items

---

core/Utils.vala
data/maya.gresource.xml
data/style/ColorButton.css
src/SourceDialog/SourceDialog.vala

Adds a quick radio button color selector instead of using a Gtk.ColorButton

SourceDialog.vala: Choose colors from the palette

---

data/style/calendar.css

This removes internal variables and makes it depend on stylesheet variables, cleans up some indentation, opts for shading instead of manually mixing with white, and uses CSS gradients instead of GTK ones.

Simplify calendar CSS

---

data/style/calendar.css
src/Grid/GridDay.vala

Fixes #295 
Makes the contrast between regular days and other month days higher

calendar.css: Fix RTL borders, high contrast

---

src/SourceDialog/SourceDialog.vala

Since for layout purposes we want to treat the collection of radios like a single widget, this adds them all to their own grid and simplifies some of the other grid layout.
Fixes #310

Put color radios in their own grid

---

src/AgendaView.vala

Since we already have headers on these sections, I don't think this is any less clear and it gives us more room for events.

AgendaView: Remove Upcoming Events label

---

src/Widgets/AgendaEventRow.vala

Proposing for multi-line event titles. I think the top-aligned looks better, and more in line with the text baseline.

top-align agenda event icons

---

src/AgendaView.vala

* Bump copyright header
* Row and column spacing are 0 by default, don't need to specify
* Use `xalign` property instead of `set_alignment ()`
* Use Granite style class constants
* Remove unnecessary sep `hexpand`s
* `add` instead of `attach`
* Explicit method scope
* Remove unused method

AgendaView: misc cleanup

---

src/Widgets/CalendarButton.vala

* Bump copyright header
* Subclass Gtk.MenuButton instead of ToggleButton
* Use built-in popover and get rid of code about showing and hiding it
* Use new features of Gtk for scrollbox max content height
* Make a single-use function into a lambda
* Reduce scope of `list_box`

CalendarButton: subclass MenuButton, cleanup

---

src/EventEdition/EventDialog.vala

Get rid of this single-use method

EventDialog: Remove build_dialog method

---

data/style/calendar.css

More closely matches the date selection CSS from wingpanel and doesn't interfere so much with event colors

Calendar.css: match wingpanel's date selection CSS

---

src/AgendaView.vala

One big happy events list. Makes it a lot easier to see upcoming events

AgendaView: Use one scrolledwindow for events list

---

src/MainWindow.vala

Stops being able to launch an event editing dialog when you activate an event in the grid or agenda views

MainWindow: don't allow editing read-only events

---

src/SourceDialog/SourceDialog.vala

If you try to create a new calendar without changing the color, you can't add a new calendar:
By launching Calendar from Terminal, I got the following error message:
```
** (io.elementary.calendar:17789): CRITICAL **: 12:15:47.198: maya_local_backend_real_add_new_calendar: assertion 'color != NULL' failed
```
However, you can add when you select the color of the calendar explicitly:
You can create a new calendar even if you don't change the color.

Initialize hex_color with default selected red color

---

src/SourceDialog/SourceDialog.vala

When you create a new calendar, the red radiobutton (`color_button_red`) is selected for the color of calendar by default. However, once you try to edit existing calendars ("Personal" or "Birthdays & Anniversaries"), no radiobutton is selected (actually an hidden raddiobutton, `color_button_none`, is selected because the color of these calendars is not listed in the default color palette). And then if you try to create a new calendar, the red radiobutton is no longer selected by default, since the hidden radiobutton is still selected.
This PR explicitly select the red radiobutton when users try to create a new calendar.

Set color_button_red active when creating a new calendar

---

src/AgendaView.vala

This fixes #396 by setting `hexpand` to `true` for the relevant components in the Agenda sidebar.
We should also consider constraining the size of the calendar grid so the user can't resize to an unnecessarily skinny grid, and a fat Agenda.

Explicitly set hexpand to true for agenda components

---

core/Model/CalendarModel.vala
core/Utils.vala
daemon/Daemon.vala
meson.build
src/EventEdition/GuestGrid.vala
src/EventEdition/GuestsPanel.vala
src/EventEdition/InfoPanel.vala
src/EventEdition/LocationPanel.vala
src/EventEdition/ReminderPanel.vala
src/EventEdition/RepeatPanel.vala
src/ImportDialog.vala
src/Widgets/EventMenu.vala

This looks minimal thanks to the previous PRs.
Fixes #404

Add compatibility with libecal-1.2 and libical-glib

---

src/AgendaView.vala

Fixes #452 
When the month or year is changed on the calendar the new parameters cause the source to be reloaded, this will trigger on_events_added but not on_events_removed. To handle this I have connected to parameters_changed and delete existing rows, this is similar to the handling in the CalendarView although that runs on idle removing events and then syncing with the model, such a implementation here would require quite complex handling here to avoid duplication from the subsequent on_events_added signal.

Reset AgendaView items when parameters change

---

data/style/Grid.css

Fixes #399 
The more label was set to white by the elementary stylesheet when selected, this sets text colour for cell as @fg_color and so it stays visible when selected.

Stop more label becoming white when selected

---

src/EventEdition/ReminderPanel.vala

Fixes saving reminders with eCal below 2.0.
Fixes #459, #469
Related to #474 however not necessarily the cause.

Correctly set reminder type when saving

---

core/Utils.vala
src/EventEdition/InfoPanel.vala
src/Widgets/AgendaEventRow.vala

Fixes #463
Small fix to avoid repeating the same time for an event. However, the app didn't allow to create events with the same time in the start and in the end, so a small change was made there too.

Avoid repating event time if end equals start

---

data/io.elementary.calendar.appdata.xml.in
meson.build

https://github.com/elementary/calendar/compare/5.0.3...master
**Changelog:**
<p>Minor Updates:</p>
<ul>
<li>Correctly save event reminders</li>
<li>Ellipsize event participant details if necessary</li>
<li>Fix unwanted rescheduling when editing event title</li>
<li>Updated translations</li>
</ul>

release 5.0.4

---

src/Application.vala

The docs on SettingsSchemaSource get_default say
```
The returned source may actually consist of multiple schema sources from different directories, depending on which directories were given in `XDG_DATA_DIRS` and `GSETTINGS_SCHEMA_DIR`. For this reason, all lookups performed against the default source should probably be done recursively.
```
Without this in NixOS it will not work as intended, as we
have multiple entries in XDG_DATA_DIRS.

Application: lookup schemas recursive

---

src/EventEdition/RepeatPanel.vala
vapi/libical.vapi

Fixes #508 
Second option for the monthly recurring events is displayed wrongly when editing event. Even when event is created with either options. 
- Second option's text is updated with first day's value, code was looping over all days which created the issue
- New method added to VAPI for `ICal` to get single value from `by_day` attribute

Second option for Monthly recurrence is displayed when editing an event

---

src/EventEdition/RepeatPanel.vala
vapi/libical.vapi

Fixes #487
Monthly repeat of an event by the same day was using `by_month` attribute instead of `by_month_day` attribute in `ICal.Recurrence`. Using `by_month_day` attribute solves the problem.
- Monthly repeats by day are now using `by_month_day` attribute
- New methods were added to ICal's VAPI to work on `by_month_day` attribute of the `ICal.Recurrence` according to the documentation of the library

Monthly repeats by the same day should use 'by_month_day' attribute

---

core/Model/CalendarModel.vala
po/extra/mr.po
src/Widgets/EventMenu.vala
vapi/libecal-1.2.vapi

Fixes #491
VAPI for `libecal-1.2` was wrong that caused to send address of the pointer instead of the pointer itself. Program was crashing with _Segmentation fault_ due to invalid access to an address. Problem was explained in detail at [this comment](https://github.com/elementary/calendar/issues/491#issuecomment-611752958) of the issue report. Solving VAPI problem revealed another problem which was more dangerous than _Segmentation fault_ error of the problem, that may broke down event of the user. When user selects _Remove occurrence_ menu item, misbehavior occurs and only right-clicked event remains and other occurrences will be deleted. I found that instead of calling `update_event` method to update whole event by adding exception date, we can rely on `remove_event` method in …

Fix behavior of removing occurrences of recurrent events

---

core/Model/CalendarModel.vala

Being more explicit can't hurt. 
It's not in the vapi (or on valadoc.org, interestingly), but in the source this function returns a nullable value.

Add nullable annotations

---

po/POTFILES

One of multiple PR's to break [Calendar.Store](https://github.com/elementary/calendar/pull/549) down in smaller chunks to make review easier. This one contains:
- Added missing files to `pot/POTFILES` and dropped no longer needed ones

Calendar.Store: Update for pot/POTFILES

---

core/GesturesUtils.vala
core/Services/Calendar/Store.vala
core/Utils.vala
core/meson.build
daemon/Daemon.vala
plugins/CalDAV/CalDAVBackend.vala
plugins/Google/GoogleBackend.vala
po/POTFILES
src/AgendaView.vala
src/Application.vala
src/EventEdition/EventDialog.vala
src/EventEdition/RepeatPanel.vala
src/Grid/CalendarView.vala
src/Grid/EventButton.vala
src/Grid/Grid.vala
src/Grid/GridDay.vala
src/ImportDialog.vala
src/MainWindow.vala
src/SourceDialog/SourceItem.vala
src/SourceDialog/SourceSelector.vala
src/Widgets/CalendarButton.vala
src/Widgets/DynamicSpinner.vala
src/Widgets/EventMenu.vala
src/Widgets/HeaderBar.vala

One of multiple PR's to break [Calendar.Store](https://github.com/elementary/calendar/pull/549) down in smaller chunks to make review easier. This one contains:
- Renamed `Maya.Model.CalendarModel` to `Calendar.Store`

Calendar.Store: Renamed Maya.Model.CalendarModel to Calendar.Store

---

vapi/libecal-1.2.vapi

One of multiple PR's to break [Calendar.Store](https://github.com/elementary/calendar/pull/549) down in smaller chunks to make review easier. This one contains:
- Changed vapi to support completing a task (needed to compile new `Calendar.Store`)

 Calendar.Store: vapi changes to complete a task

---

src/EventEdition/EventDialog.vala
src/EventEdition/RepeatPanel.vala

Fixes #11 
I have no experience with localization, so I hope this is all in an acceptable format. I couldn't find a way to add a context annotation to a plural string, which seems weird. This could interfere in some languages like German, where the noun is in a different case and takes a different form than the default. But at any rate this is an improvement.

Add contextual translations for "Repeat" string

---

core/Services/Calendar/Util/DateTime.vala
core/Services/Calendar/Util/ICalComponent.vala
core/Services/Calendar/Util/ICalTime.vala
core/Tests/meson.build
core/Tests/util-tests.vala

Fixes issues with time zones, where we erroneously fell back to UTC times instead of properly treating floating time information. This was most visible for all-day events, which are all floating by definition, and caused out-of-order errors.
I think this fixes all the surface area that floating time zones could hit. If you find any more, please let me know and I'll fix it.
Fixes #577

Implement floating timezones

---

src/EventParser/Parsers/ParserEn.vala

Merges the two 'to' patterns, the first one masked the second one as the 'to' would be caught regardless of the 'from'.
Fixes #576 as the merged one does not have this issue as it requires times in the pattern.

Merge patterns for 'to'

---

core/Tests/util-tests.vala

I messed up how I handled the `$TZ` environment variable reset in `util_tests.vala` in my last PR. The issue shouldn't have any significant impact (it only resets the variable to what it was before, which is local to the shell session anyway) but this fixes it.

Fix compiler warning in util_tests

---

core/Services/Calendar/EventStore.vala

Fixes #478 
Re-implements the fix from #560. When an event appears multiple times with the same UID, we only take the first one. This shouldn't catch any recurrences, since those differ by RID, not UID.
A test would be nice, but I don't know how to mock a google backend for this. :man_shrugging:

Fix showing duplicate events when added

---

data/io.elementary.calendar.appdata.xml.in
src/SourceDialog/SourceDialog.vala

Fixes #550 
This keeps the state of the check button to set a calendar as default in the right state. When you open the calendar edit dialog, it always reverts to unchecked, and checking it will tell Calendar to make that calendar the default. If it's not checked, then nothing happens and the default calendar stays as is.
I'm not convinced this is a great design, but it at least fixes the issues we had before. It means that (outside of what appears when you create a new event) there's no indication of which is default. But as far as I can tell, this PR just fixes the current design, so any redesign can be done later.
If this gets approved I'll update appdata.xml then to avoid conflicts.

Fix checkbox to set calendar as default

---

src/Widgets/EventMenu.vala

On Odin, the event context menu was appearing empty.  This fixes it.

Show all event menu items

---

data/style/AgendaEventRow.css

Fixes #612 
Fixes #267 
When combined with https://github.com/elementary/stylesheet/pull/852 relies on the stylesheet to set accent-based foreground and background colors

AgendaEventRow.css: Rely on stylesheet for colors

---

core/Services/Calendar/EventStore.vala
core/Services/Calendar/Util/DateIterator.vala
core/Services/Calendar/Util/DateTime.vala
core/Tests/eventstore-tests.vala
core/Tests/util-tests.vala
src/Grid/CalendarView.vala

Fixes #634 
This PR makes it so that events occurring on the last day of the month and grid will properly appear in their respective ranges. I had to make some fixes elsewhere that assumed the old behavior to get this to work. I also added tests for these behaviors.

Make EventStore ranges inclusive

---

src/Grid/EventButton.vala
src/Widgets/AgendaEventRow.vala
src/Widgets/SourceRow.vala

Gtk.CssProvider fails if when setting `accent_color` to a RGBA value, this PR make sure that we are setting  only the RGB part of the hex color if we recevie a RGBA one.

Strip Alpha From Calendar Color if Needed

---

data/io.elementary.calendar.appdata.xml.in

I played with other combinations and thought this looked the nicest. Any green background felt too heavy and lost the icon too much.

AppData: Use white/Lime 900 for brand banner

---

core/Services/Calendar/Util/ICalTime.vala
src/Application.vala

Also add code to release the internal cache at the end of the program

Revert "utils: Workaround wrong ICal.Time.get_timezone() binding to fix memleak (#719)"

---

README.md
data/io.elementary.calendar.appdata.xml.in
meson.build
src/EventEdition/InfoPanel.vala

Uses `Granite.HyperTextView` for the comment textview of an event. This allows to Ctrl + Click on an existing hyperlink in the event description.
Makes https://github.com/elementary/calendar/pull/692 obsolete.

Granite.HyperTextView: Support for clickable hyperlinks in event description

---

src/SourceDialog/SourceDialog.vala

Fixes an issue reported in #553. Previously we didn't check whether a calendar is read-only, so you could set it as default, with some strange results. This fixes that by disabling the checkbox.
Since a disabled checkbox can now mean multiple things (read-only calendar if unchecked, or already default if checked), should we add a label explaining why it's disabled? I'm not sure if that's necessary, but it could be helpful.

Make default calendar checkbox insensitive if read-only

---

core/Tests/eventstore-tests.vala
core/Tests/util-tests.vala

What it says on the tin. For unit tests, you're supposed to use `GLib.assert_true` instead of `GLib.assert`, which may be disabled by compilation flags. See https://docs.gtk.org/glib/testing.html.

Use assert_true instead of assert in tests

---

src/EventEdition/RepeatPanel.vala

Fixes #759 
Description of the reasoning there. The array has a special terminator value, which I added a check for. If it's encountered, stop looping over the array, since further entries are no longer valid.

Add check for termination of by_day_array

---

src/Grid/GridDay.vala

GLib 2.73.1 [no longer fires notify signal for properties set during instantiation](https://gitlab.gnome.org/GNOME/glib/-/commit/8851112b8de024ff6fb4235a4475ffa6c98973dc). This resulted in the label remaining empty. Now, the `Grid.update_day` would also run and set `date` property but that did not have an effect – probably because the date did not change.
We need to set the initial label ourselves. To avoid code duplication, we can just use `GBinding`.
Fixes: https://github.com/elementary/calendar/issues/761
cc @bobby285271

Fix day in month in Grid with GLib 2.73.1+

---

core/Tests/meson.build

Since I am already fixing the other repos with this issue, I thought I might do it here aswell.
TLDR: meson will change the default behaviour of `run_command` and displays that as a warning when building.
See: https://github.com/mesonbuild/meson/issues/9300

Fix meson warning for run_command

---

data/io.elementary.calendar.gschema.xml
src/Application.vala
src/MainWindow.vala

GTK 4/Wayland prep. Can't set window position in Wayland

gschema: remove window position

---

src/AgendaView.vala
src/Widgets/HeaderBar.vala

Re-arranges some header items so that they are more closely associated with the pane they directly act on:
* The calendar settings and export buttons move to the calendar pane since the export button acts on the default calendar, not the currently visible agenda items, and the settings popover affects which calendars are shown in the calendar view
* The create new event button is now in the agenda pane since the event will be created for the selected day as labeled in this pane
* The agenda pane's label moves up into the header to make more room for events

Rearrange headerbar items

---

core/Utils.vala
plugins/Web/WebBackend.vala
plugins/Web/meson.build
plugins/meson.build

Support online web calendar

---

io.elementary.calendar.yml

libportal is bundled from Platform 8 so we shouldn't need it here anymore

Flatpak: Use libportal from Platform

---

src/Widgets/CalendarRow.vala

* Replace Box with Grid
* Modern code style

CalendarRow: cleanup

---

core/Backends/PlacementWidget.vala
plugins/CalDAV/CalDAVBackend.vala
plugins/Web/WebBackend.vala
src/SourceDialog/SourceDialog.vala

Make sure all of the widgets in SourceDialog are visible to the screen reader

SourceDialog: fix screen reader labels

---

src/Widgets/SourceRow.vala

* Make sure these buttons can be accessed with the keyboard or via touch
* Don't need to add "flat" (relief style none) on image buttons
* Remove destructive styling from trash because it looks broken

SourceRow: always show buttons
