src/AgendaView.vala
* Use DIM_LABEL class instead of setting sensitive and opacity
* Use xalign instead of set_alignment
* Use wrap property instead of set_line_wrap
* en dash instead of hyphen
=> Fix up Agenda View styling a little

src/Widgets/ContractorButtonWithMenu.vala
=> Rewrite ContractorButtonWithMenu as a GtkMenuButton subclass

core/Utils.vala, src/EventEdition/InfoPanel.vala
Handles all day events correctly when getting local datetimes from ical components
Fixes #141
=> Correct date ranges in Agenda

src/Widgets/CalendarButton.vala
* Add an arrow to the end of the button to imitate Gtk.ComboBox
* Change `button_grid` to `calendar_grid`
* Remove unnecessary `set_alignment`
* Add a minimum width to the popover to more closely match the button width
* Code style
* Organize
=> CalendarButton.vala: add arrow, misc cleanup

src/Application.vala, src/CMakeLists.txt, src/MainWindow.vala
Proposing before this diff gets real big:
* Create a MainWindow class and begin using it
* Update copyright headers
* Fix whitespace
* Remove unnecessary comments
* Reduce variable scope where possible
* Code style
* Organize
=> Add a MainWindow and move a couple things to it

src/Application.vala, src/MayaToolbar.vala
It would be nice to re-implement a search at some point, but this code is dead so removing it
=> Remove dead code related to a searchbar

src/Grid/WeekLabels.vala
Fixes right clicking week labels to allow hiding them.
=> Allow right clicking week labels

src/Application.vala
Shows it in the help menu and stops the warning about it being an unrecognised option.
Fixes #189
=> Add debug option to app_options

core/Backends/LocalBackend.vala
=> Store local calendar edits

core/Utils.vala, src/AgendaView.vala, src/Grid/EventButton.vala, src/SourceDialog/SourceItem.vala, src/Widgets/CalendarButton.vala
The override_color and override_background_color functions are deprecated.
=> Style calendar colours using css

debian/maya-calendar.1
Updates the options in the man page as they are quite outdated. Also removes the iCal import bug, there are only two open 'Confirmed' bugs and tagged releases don't matter to end users so I have added the email notifications bug.
=> Update man page

src/Grid/EventButton.vala, src/Grid/GridDay.vala
=> Focus GridDay on clicking EventButton

src/Application.vala
It also used deprecated method.
=> Remove unused match_keycode

.travis.yml
=> Test with Houston CI

src/Widgets/HeaderBar.vala
=> Fix month name format

.travis.yml
=> update travis file to new houston

src/SourceDialog/SourceDialog.vala
* Adjust margins
* Remove extra widget
* Organize
* Remove unnecessary casts
* Bump copyright
=> SourceDialog: misc cleanup

README.md, meson.build, src/MainWindow.vala, src/Widgets/HeaderBar.vala
* Use GLib.Action for the new event and go to today actions
* Add shortcut accelerators
* Use the new Granite tooltip markup
=> Use GLib.Action and add shortcuts

core/Settings/SavedState.vala, data/io.elementary.calendar.gschema.xml, src/Application.vala, src/MainWindow.vala
Using the same way we save and restore window state in the new Mail
=> Rewrite window state saving

core/Utils.vala
Depends on #303
This is unused
=> Utils: remove set margin method

src/Widgets/AgendaEventRow.vala
=> AgendaEventRow: Make date label small

src/Grid/EventButton.vala
* Bump copyright
* Organize
* Reduce variable scope
* GObject style
* Implicit typing
* White space
=> EventButton: misc clean up

src/AgendaView.vala
Merge after #315 
Removes the background and separator behind the sidebar header and adds a bit of padding
=>  AgendaView: Remove background and adjust padding

src/AgendaView.vala, src/Widgets/AgendaEventRow.vala
Fixes a rendering error in the scrolled box when resizing the window and DRY setting row headers
=> AgendaView: Fix a rendering error in scrollbox

data/style/AgendaEventRow.css, src/Grid/EventButton.vala
=> EventButton: match style with agendaview events

data/style/calendar.css
Softens up the appearance of the calendar a bit
=> Calendar.css: Use sep color from stylesheet

src/Widgets/AgendaEventRow.vala
=> AgendaEventRow: make labels selectable

src/SourceDialog/SourceItem.vala, src/SourceDialog/SourceSelector.vala, src/Widgets/CalendarButton.vala
Fixes a bug where these header items can be selected
=> Replace SourceItemHeader with Granite.HeaderLabel

src/Widgets/AgendaEventRow.vala
Add a revealer so we animate when a location is added to or removed from an event
=> AgendaEventRow: Animate appearance of location label

core/Utils.vala, src/Widgets/CalendarButton.vala
Instead of the awkward rectangle
=> Make calendar color rounded

po/POTFILES, src/Grid/CalendarView.vala, src/Grid/EventButton.vala, src/Grid/Grid.vala, src/MainWindow.vala, src/Widgets/EventMenu.vala, src/meson.build
I want to re-use this menu in the sidebar in a future commit, so it needs to be separated from the EventButton
=> Create EventMenu class

core/Settings/LanguagesFormat.vala
=> Use short day name

src/Widgets/DynamicSpinner.vala
* Reduce variable scope
* Whitespace
* Use MenuButton
* Center button vertically 
* Make the stop icon symbolic
=> DynamicSpinner: misc cleanup

debian/libmaya-calendar0.symbols
=> Symbols: Remove maya_util_style_calendar_color

core/Utils.vala, src/Widgets/CalendarButton.vala
This Util is only ever used here so move it and simplify
=> Move calendar color style from Utils to CalendarButton

data/style/AgendaEventRow.css, src/AgendaView.vala, src/MainWindow.vala, src/Widgets/AgendaEventRow.vala
* Make the events look not ugly in the sidebar
* Make events keyboard activatable
* Pass events through the eventbox to the listbox
* Left align datetime label so it can be clicked through for activation
* Remove now unused modified signal stuff
=> Make AgendaView keyboard navigatable

src/EventEdition/GuestGrid.vala
* Set label style with CSS instead of in Pango
* Remove unnecessary casts
* Remove an extra grid
* Remove one-line method
* Organize
=> GuestGrid: misc cleanup

core/config.vala.in, core/meson.build, daemon/Daemon.vala, src/Application.vala
=> Application: Remove version from CLI

core/config.vala.in, core/meson.build, src/Application.vala
Gtk.Application already sets all this for us
=>  Application: don't redundantly set localization

src/Application.vala
Since we're a Gtk.Application we don't need to do this
=> Application: don't handle main loop manually

core/Model/CalendarModel.vala, core/Settings/MayaSettings.vala, src/EventEdition/RepeatPanel.vala
Matches https://github.com/elementary/wingpanel-indicator-datetime/pull/180
=> Use GLib.DateWeekday

core/Utils.vala, data/maya.gresource.xml, data/style/Grid.css, data/style/Header.css, data/style/WeekLabels.css, src/Grid/CalendarView.vala, src/Grid/Grid.vala, src/Grid/GridDay.vala, src/Grid/Header.vala, src/Grid/WeekLabels.vala
Instead of one big CSS file, add specific ones for each class
=> Add specific CSS files per class

debian/libmaya-calendar0.symbols
=> Symbols: remove maya_settings_weekday_get_type

debian/libmaya-calendar0.symbols
=> Symbols: Remove is_day_in_range

debian/libmaya-calendar0.symbols
=> Symbols: remove css class

data/io.elementary.calendar.appdata.xml.in
ahead of an actual 5.0.1 release so we can get translations in
=> AppData: Update release information

data/io.elementary.calendar.appdata.xml.in, meson.build
=> Release 5.0.1

.github/workflows/main.yml, daemon/Daemon.vala
=> Add Lint to CI

data/io.elementary.calendar.appdata.xml.in, meson.build
=> Release 5.0.2

data/io.elementary.calendar.appdata.xml.in, src/EventEdition/LocationPanel.vala
=> LocationPanel: handle possible null geo

src/EventEdition/ReminderPanel.vala, src/EventEdition/RepeatPanel.vala
=> Replace Gtk.Toolbar with Gtk.ActionBar

po/ar.po, src/SourceDialog/SourceSelector.vala
=> SourceSelector: Use Gtk.ModelButton instead of style class

src/Widgets/AgendaEventRow.vala
Fixes #533.
Description and motivation there.
=> Make sidebar labels not selectable

core/Tests/meson.build
=> core: do not run tests depending on uninstalled locales

data/io.elementary.calendar.appdata.xml.in
Forgot to do this in #597 (sorry)
Is this the right way to start adding release notes after a release was just published?
=> Update appdata.xml for duplicate events fix

data/io.elementary.calendar.appdata.xml.in, meson.build
One last fix before we get all Hdy with it?
=> Release 5.1.1

src/SourceDialog/SourceDialog.vala
This column spacing is out of control
=> SourceDialog: reduce color button column spacing

src/Widgets/DateSwitcher.vala, src/Widgets/HeaderBar.vala
* Gobject-style construction
* Bump copyright
* Remove extra margins
* Remove vexpand
* Remove workaround for old stylesheet
* other code style
=> DateSwitcher: GObject and code style

src/MainWindow.vala, src/Widgets/DateSwitcher.vala, src/Widgets/HeaderBar.vala
View with hide whitespace changes
=> HeaderBar: inline namespace

po/POTFILES, src/SourceDialog/SourceItem.vala, src/Widgets/HeaderBar.vala, src/Widgets/SourcePopover.vala, src/Widgets/SourceRow.vala, src/meson.build
=> SourceSelector -> SourcePopover

src/SourceDialog/SourceDialog.vala
To match https://github.com/elementary/switchboard-plug-pantheon-shell/pull/247
=> SourceDialog: Re-order accent colors

src/SourceDialog/SourceDialog.vala, src/Widgets/AgendaEventRow.vala
Fixes #561 
(Or at least one problem with it)
Now, all text labels in an `AgendaEventRow` use the `WORD_CHAR` wrap mode, which should make them flexible when need be.
=> Wrap location label in AgendaView

.github/workflows/main.yml, io.elementary.calendar.yml
=> Add flatpak

src/EventEdition/ReminderPanel.vala
=> ReminderPanel: fix reminders edition

src/MainWindow.vala
=> MainWindow: fix calview assignment

.github/workflows/ci.yml
* Only run CI on PRs
* Update flatpak build
=> CI: Update flatpak action

src/Widgets/AgendaEventRow.vala
New:
Old:
I also did some code style updates.
=> Use Granite small label class for AgendaEventRow

.github/workflows/ci.yml, io.elementary.calendar.yml
* Use our container
* Set branch to "daily"
* Remove redundant meson build
=> CI: Update Flatpak action; remove redundant build

daemon/Daemon.vala
this makes the daemon stores all the alarms for a event instead of only one.
fixes #676
=> Daemon: Use `Gee.HashMultiMap`

po/POTFILES
Fixes the merge error - sorry, always forget this one:
https://github.com/elementary/calendar/runs/3588140954
=> Fix POTFILE

io.elementary.calendar.yml
No longer needed because of new settings portal
=> Flatpak: Remove accountsservice hole

src/Application.vala
This fixes a compilation error with latest valac which doesn't allow the option
variables to be less accessible than the OptionEntry.
=> Application: Make the option fields internal to the Application class

data/icons/128.svg, data/icons/16.svg, data/icons/24.svg, data/icons/32.svg, data/icons/48.svg, data/icons/64.svg
* Update to new round rect shape
* Use latest color palette
=> Modernize app icon

data/io.elementary.calendar.appdata.xml.in, meson.build
=> Release 6.1.3 (#784)

.github/workflows/ci.yml
Since we're not actually shipping in Flatpak right now we should build against the OS
=> CI: build with meson

data/icons/16/event-new-symbolic.svg, data/icons/16/event-new.svg, data/icons/24/event-new.svg, data/io.elementary.calendar.desktop.in, data/io.elementary.calendar.gresource.xml, data/meson.build, meson.build
non-fd.o icon name
* Gresource it for use inside the app
* Install it to a namespace we're allowed to export in Flatpak for the Launcher action
=> Include new event icon
